[build]
  # Building from repository root now that duplicate nested folder is removed
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Set these in the Netlify UI if you want to override
  VITE_API_URL = "https://server.buzztalk.me"
  VITE_SOCKET_URL = "https://server.buzztalk.me"
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://server.buzztalk.me/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://server.buzztalk.me/socket.io/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
